### ISSUE TITLE
Medeaquerry support

### ISSUE THREAD

**Issue by LProemer** [jhildenbiddle/css-vars-ponyfill#100]
Tested with IE11. 

Following code should work according to the specifications but do not with the ponyfill:

```
:root {
  --max-input-width: 250px;
}
@media screen and (min-width: 750px) {
  :root {
    --max-input-width: 500px;
  }
}
```

What it should do:
When the window with is over 750px then the --max-input-width should be set to 500px;

What happens in IE11 with the ponyfill.
Everything in the media-querry is ignored.

**Comment by jhildenbiddle** [comment]
Hey @LProemer,

Unfortunately, `@meda` rules are not currently supported. See #31 for details.
