### ISSUE TITLE
Seems like it's working but no variables were changed

### ISSUE THREAD

**Issue by Raemy92** [jhildenbiddle/css-vars-ponyfill#102]
Hi

I already brought your great library to work but since today I have trouble changeing the vars. I use this lib for my WordPress testing site with a custom theme and theme options.

I created a FileWriter in PHP which writes the vars in a JS object. This object is includet in the cssVars() function:

`cssVars({
    // Targets
    rootElement: document,
    shadowDOM: false,

    // Sources
    include: 'link[rel=stylesheet],style',
    exclude: '',
    variables: ievars,

    // Options
    onlyLegacy: false,
    preserveStatic: true,
    preserveVars: false,
    silent: false,
    updateDOM: true,
    updateURLs: true,
    watch: false,

    // Callbacks
    onBeforeSend(xhr, elm, url) {
        console.log('start with vars: ' + ievars);
    },
    onWarning(message) {
        console.log('warning');
    },
    onError(message, elm, xhr, url) {
        console.log('error');
    },
    onSuccess(cssText, elm, url) {
        console.log('success!!');
    },
    onComplete(cssText, styleElms, cssVariables, benchmark) {
        console.log('complete');
    }
});`

In the console it seems like everythings working since I get the output "start with vars..." and "success!" but nothing has changed in the source-code.

My ievars looks something like this after writing it:
`var ievars = {
'--bgcolor': '#F7FFF6',
'--bgheader': '#C3FFAD',
'--bgfooter': '#505D90',
'--bgteaser': '#FFBE77',
'--colortext': '#212123',
'--colorlink': '#3775FF',
'--colorlinkhover': '#50B9DD',
'--h1color': '#505D90',
'--h2color': '#505D90',
'--h3color': '#212123',
'--h4color': '#212123',
'--h5color': '#212123',
'--h6color': '#212123',
'--menulinkfarbe': '#FF5151',
'--menulinkfarbehover': '#FF9D9D',
};`

Maybe you someone sees an error, I'm feeling like it's a very stupid error by me, because it worked at some point. But I can't really find it today. :)

**Comment by Raemy92** [comment]
It's working now: I imported the CSS styles with `@import url(../layouts/1/style.css);` and changed it to `@import "../layouts/1/style.css";`

Great library, cheers!

**Comment by jhildenbiddle** [comment]
Glad you got it figured out.

FYI, the issue with with your original `@import` statement is that you were missing quotes within the parens.

```css
/* Works */
@import url("../layouts/1/style.css");

/* Does not work */
@import url(../layouts/1/style.css);
```
