### ISSUE TITLE
<link media="" > seems to get bugged

### ISSUE THREAD

**Issue by sueharaluke** [jhildenbiddle/css-vars-ponyfill#103]
First, thank for this ponyfill !

Rarelly people add css with media query (see below), but it gets bugged.
```html
<link rel="stylesheet" href="pc.css" media="screen and (min-width:768px)">
<link rel="stylesheet" href="sp.css" media="screen and (max-width:767px)">
```

Didn't look too much into it, but I'm guessing that the injected <style> doesn't take into account the media query.
Maybe automatically add it if present ? 
```html
<style>@screen and (min-width:768px) { .injected-css {}  }</style>
<style>@screen and (max-width:767px) { .injected-css {}  }</style>
```

Again, this is a rare case, for 2 reasons: 1. only a few people add css like this, 2. I could add the option to ignore the sp.css but didn't like the idea.

I just added the media query inside of the css, so I'm good for now, but I thought it might be worth pointing this out.

Cheers !

**Comment by jhildenbiddle** [comment]
Thanks for filing the issue, @sueharaluke.

This falls under the "make the ponyfill work with more than just `:root` selectors" requests which has been covered several times already: https://github.com/jhildenbiddle/css-vars-ponyfill/issues/5, https://github.com/jhildenbiddle/css-vars-ponyfill/issues/26, https://github.com/jhildenbiddle/css-vars-ponyfill/issues/31, and https://github.com/jhildenbiddle/css-vars-ponyfill/issues/58.

Closing as duplicate.
