### ISSUE TITLE
SyntaxError: Expected token ')' in old browser

### ISSUE THREAD

**Issue by dongnaebi** [jhildenbiddle/css-vars-ponyfill#111]
![image](https://user-images.githubusercontent.com/6902417/74628943-ef974f00-5191-11ea-8a71-cdf4a8e85dc4.png)

version:2.1.3

looks like babel's problem

**Comment by ryo-utsunomiya** [comment]
I've also encountered this error. 2.1.2 is OK so looks like an issue of 2.1.3.

**Comment by tabuechn** [comment]
+1

**Comment by jhildenbiddle** [comment]
Very sorry about this, folks. 

There was a packing issue with the npm distributable. The source code here on GitHub does not produce this issue and passes all tests. I will publish a fix and very all modules transpire correctly later tonight.

Thanks for the heads up!

**Comment by jhildenbiddle** [comment]
Fixed in 2.1.4
