### ISSUE TITLE
cssVars(): variable is undefined

### ISSUE THREAD

**Issue by mlli2** [jhildenbiddle/css-vars-ponyfill#117]
Hello! Just trying to understand what I'm doing wrong or if I'm trying to do something that the library does not support. I have some css vars that I'm declaring via javascript:
`html.style.setProperty('--contentWidth', `${contentWidth}px`);`

Afterwards I call 
```
cssVars({
    onlyLegacy: false,
    onComplete: function(cssText, styleNodes, cssVariables, benchmark) {
        console.log(cssVariables)
      }
});
```

When the page renders, I spammed with messages stating that `--contentWidth` is undefined, presumably from all the elements that use that variable in their styling. Is this type of usage not supported or am I missing something more fundamental?

**Comment by mlli2** [comment]
My guess is that even though `:root` refers to the `html` element, because I'm setting with javascript I'm conflating root css variables with inline css variables?

**Comment by jhildenbiddle** [comment]
The ponyfill reads custom property values from `<style>` and `<link>`  elements, or you can set values using [options.variables](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=variables). See the [Usage](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=usage) section of the [documentation](https://jhildenbiddle.github.io/css-vars-ponyfill/) for an example.

**Example 1: Custom properties via `<style>` (or `<link>`)**

```html
<style>
  :root {
    --contentWidth: 100px;
  }

  div {
    width: var(--contentWidth);
  }
</style>
```

```js
cssVars({
    onlyLegacy: false,
    onComplete: function(cssText, styleNodes, cssVariables, benchmark) {
        console.log(cssVariables)
      }
});
```

**Example 2: Custom properties via `options.variables`**

```html
<style>
  div {
    width: var(--contentWidth);
  }
</style>
```

```js
cssVars({
    onlyLegacy: false,
    variables: {
      '--contentWidth': '100px'
    },
    onComplete: function(cssText, styleNodes, cssVariables, benchmark) {
        console.log(cssVariables)
      }
});
```

Hope this helps.
