### ISSUE TITLE
Cannot read property 'disabled' of null

### ISSUE THREAD

**Issue by vinchilive** [jhildenbiddle/css-vars-ponyfill#121]
I get this error on page load after updating to 2.3.0

```
css-vars-ponyfill.esm.js:1380 Uncaught TypeError: Cannot read property 'disabled' of null
    at t (css-vars-ponyfill.esm.js:1380)
    at css-vars-ponyfill.esm.js:1390
    at Array.some (<anonymous>)
    at r (css-vars-ponyfill.esm.js:1386)
    at css-vars-ponyfill.esm.js:1427
    at Array.some (<anonymous>)
    at MutationObserver.<anonymous> (css-vars-ponyfill.esm.js:1422)
```
on line `return isStylesheet && !node.sheet.disabled;`

maybe implement some getter like this?
```
isDisabled(node) {
    return node.sheet ? node.sheet.disabled : node.disabled
}
```

**Comment by jhildenbiddle** [comment]
Thanks, @vinchilive.

Looks like the ponyfill is detecting an `<link>` mutation before the associated stylesheet has loaded, therefore the ponyfill is unable to read `node.sheet` properly. I've [added a simple getter](https://github.com/jhildenbiddle/css-vars-ponyfill/commit/538a0aad79940872491345b4c3de8d4b28b0fa35) as suggested (which also include checking for the `disabled` attribute on `<link>` nodes).

Fix available in 2.3.1.
