### ISSUE TITLE
how updateurls options will work if my URL is different

### ISSUE THREAD

**Issue by ashishsharma229** [jhildenbiddle/css-vars-ponyfill#122]
I stuck in one scenario where my all images are coming from CDN. i set updateurls  true but there is no option to tell the css var ponyfill to provide the CDN url to update in background image url. 

Please help!

**Comment by jhildenbiddle** [comment]
As stated in the docs, [options.updateURLs](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=updateurls) only affects *relative* URLs. If your images are hosted on a CDN, the URLs for those images will be *absolute*.

Relative URL:

```html
<img src="/path/to/image.jpg">
```
Absolute URL:

```html
<img src="https://mycdn.com/path/to/image.jpg">
```
