### ISSUE TITLE
Unable to boot the script

### ISSUE THREAD

**Issue by SuperSilva** [jhildenbiddle/css-vars-ponyfill#123]
Hey man, how are you?

I'm having some trouble trying to get the script up and running on my current stack despite having everything needed (I think!) and I'm hoping you could help me figuring out what's wrong.

I've installed the ponyfill on my project using yarn and i'm using directly with a bundling system I have setup. I join together on the same file everything that I need IE to support and then I load everything by using a simple feature detection. 

![pony1](https://user-images.githubusercontent.com/6674533/81826895-27fbbe80-9530-11ea-8eb1-cb7d9a5a8101.png)

On this bundle, I also have a small script to boot up anything that needs to be manually started, like the css-vars-ponyfill.

![pony2](https://user-images.githubusercontent.com/6674533/81827399-a22c4300-9530-11ea-92fd-08b8f342e04e.png)

This makes sense in my head but unfortunately...

![pony3](https://user-images.githubusercontent.com/6674533/81827545-c425c580-9530-11ea-95fe-2e2058d7d671.png)

I've also tried importing it directly on my html using a script tag url the URL you have on the documentation but the result aways the same...
Is there anything you can point out as wrong or give any hints as to why this is happening?

**Comment by jhildenbiddle** [comment]
Hey @SuperSilva --

It's hard to debug with the information provided, but one place we can start is with loading the ponyfill from CDN. There's no reason why that shouldn't work.

I've put together a quick demo here: https://stackblitz.com/edit/css-vars-ponyfill-123

Although StackBlitz uses a bundler even on basic JS projects, you can see that I'm loading the ponyfill via a `<script>` tag at the bottom of `index.html`.

Hope this helps. Let me know if you can get a similar implementation working and we'll go from there.

**Comment by SuperSilva** [comment]
Hi @jhildenbiddle ,

I've tried to add exactly the same code as the example and although it still didn't work, because I was getting a different error I was able to identify the underlying issue to be an error related to my amd structure and configurations which I was able to fix and properly run the script. :)

Thank you for your help!

**Comment by jhildenbiddle** [comment]
You bet, @SuperSilva. Happy you got it sorted out.
