### ISSUE TITLE
Variables that reference other variables are undefined

### ISSUE THREAD

**Issue by robdimarzo** [jhildenbiddle/css-vars-ponyfill#127]
Variables are undefined in legacy browsers when I declare variables that reference other variables. This might be a duplicate of #82 but there was no resolution there.

To create dark/light theming based on css variables, I am declaring scoped variables that reference root variables from a master set of design tokens. Here's an example of this concept to change background color by theme. 

Design token variables:
```
:root {
     --color-blue-800:   0, 3, 51;
     --color-grey-100:   240, 240, 246;
}
```
Scoped theme variables:
```
.theme--dark {
     --color-background: rgb(var(--color-blue-800));
}
.theme--light {
     --color-background: rgb(var(--color-grey-100));
}
```
Stylesheet:
```
body {
     background-color: var(--color-background);
}
```
I've also created a more elaborate demo on CodePen: https://codepen.io/robdimarzo/pen/oNjKGXp

In Chrome: 
![css-var-theme-chrome](https://user-images.githubusercontent.com/6054292/83355422-5e597c00-a32d-11ea-9364-4843993c3640.png)

In IE11:
<img width="1916" alt="css-var-theme-ie11" src="https://user-images.githubusercontent.com/6054292/83355426-61ed0300-a32d-11ea-980a-f02e679cef1e.png">

**Comment by jhildenbiddle** [comment]
Hey @robdimarzo --

Per the limitations listed on the [README](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/README.md) and the [docs](https://jhildenbiddle.github.io/css-vars-ponyfill): 

> **Limitations**
> - Custom property declaration support is limited to :root and :host rulesets

Scoped custom property declarations are (unfortunately) not supported. This has been covered in other issues, but the two that may be of interest are #26 (which explains why the polyfill doesn't support scoped custom properties) and #74 (specifically [this comment](https://github.com/jhildenbiddle/css-vars-ponyfill/issues/74#issuecomment-519996495) which offers a solution for swapping themes).

Hope this helps. Happy to answer any questions you may have.
