### ISSUE TITLE
IE 11 not responding due to long running script in production build (minified stylesheets)

### ISSUE THREAD

**Issue by AravinthAro** [jhildenbiddle/css-vars-ponyfill#134]
Hi guys, we are planning to use CSS variables for colors in our project. For IE 11 We have checked with this polyfill and it worked when running a local build, but not responding when running production build. I have even tried `preserveStatic` option. Is there anything I can try to fix the issue?? 
I tested with non-minified local build stylesheets, the application loads in IE 11. I guess the issue is with minified code.

**Comment by jhildenbiddle** [comment]
Hey @AravinthAro.

First, try to limit the CSS being processed until you find the rule(s), declaration(s), or stylesheet(s) that cause the issue. Once you've identified the CSS that causes the issue, share the CSS here and I'll take a look.

**Comment by AravinthAro** [comment]
I'm afraid I can't share the CSS here. But somehow I managed to make the ponyfill work. This is what I did.
```
cssText
        .split("{").join("{\n") /* {color.. -> {<new-line>color.. */
        .split("}").join("\n}") /* flex;}   -> flex;<new-line>}   */
        .split(";").join(";\n"); /* ;}       -> ;<new-line>}       */
```
I kind of beautified the minified code only for Internet explorer. 

> First, try to limit the CSS being processed until you find the rule(s), declaration(s), or stylesheet(s) that cause the issue.

But I got your point, I will do it when I get time. 

Thanks for your response.

**Comment by jhildenbiddle** [comment]
Glad you were able to find a workaround, @AravinthAro.

FWIW, I do recall someone else having an issue with minification, and I think it was related to missing quotes in an old IE `filter` declaration. If/when you identify the item(s) that cause the error, I'm happy to make the necessary updates if you share your findings here.

**Comment by jhildenbiddle** [comment]
@AravinthAro --

If I may suggest an alternate approach to fix you list above:

```js
cssText.text.replace(/([{};])/g, '$1\n');
```

This will be much, much faster than splitting a potentially large string multiple times. If you are unfamiliar with regular expressions, [regex101.com](https://regex101.com) is a great tool. You can play with the regular expression above here: https://regex101.com/r/FADIqr/1
