### ISSUE TITLE
Cannot load css file from file schema (file:///) - xhr.status = 0

### ISSUE THREAD

**Issue by marinbgd** [jhildenbiddle/css-vars-ponyfill#136]
I am working on a Tizen TV App -> its basically hybrid app (a small wrapper and HTML5/JS app inside).
Css variables are not supported on all TV models, so I use this useful "ponyfill".
There is an error when cssVar is trying to automatically get the CSS file defined in <link>.

In HTML HEAD document, there is a <link href="app.css" rel="stylesheet"> which is loaded normally.
You can see in developer tools in network ->
Request URL:file:///portal/uc/samsung/v1/app.css
and response is there too.

But when cssVars() is called, its xhr requests fails with following error:
"cssVars(): CSS XHR Error: file:///portal/uc/samsung/v1/app.css 0 Unspecified Error (possibly CORS related)"

Further inspection got me here:
- using XMLHttpRequest to get resource from file schema ("file:///") will return status 0 (not 200), and that is normal ([https://stackoverflow.com/questions/5005960/xmlhttprequest-status-0-responsetext-is-empty#:~:text=status%20is%200%20when%20your,http%20protocol%20in%20the%20browser.]
- inspecting source code of this lib I found that its only checking for status 200 for request to be successfull.
- it seems like the check must allow status 0 too.

Please respond.

**Comment by marinbgd** [comment]
If you need more explanation, or I was too unclear, write me how to clear up.

**Comment by marinbgd** [comment]
axios fixed similar issue:
https://github.com/axios/axios/pull/2470

you can check out what they added to handle urls with 'file://'

**Comment by jhildenbiddle** [comment]
Hi @marinbgd.

Apologies for the delayed response.

This issue as been fixed in #140. A new version will be released shortly.

**Comment by marinbgd** [comment]
Thanks a lot!

**Comment by jhildenbiddle** [comment]
Of course, @marinbgd. Thank you for filing the issue.

All fixed in 2.4.0. :)
