### ISSUE TITLE
Latest version re-direct isn't working

### ISSUE THREAD

**Issue by pterakopov** [jhildenbiddle/css-vars-ponyfill#143]
Hello,
we currently reference the library like so https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2 in order to use the latest 2.*.* version. The latest published version is 2.4.1 but the reference above appears to map to 2.4.0 instead. If we change it to https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2.4, it then resolves it as 2.4.1 which is correct.

**Comment by jhildenbiddle** [comment]
Hi @pterakopov,

The CDN takes ~12-24hrs to update redirects. You can always force the latest version by using the full version number:

```
https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2.4.1
```

FWIW, I just checked https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2 and it loaded 2.4.1 as expected.
