### ISSUE TITLE
Disabled attribute on link tag does not update new styles in DOM

### ISSUE THREAD

**Issue by sandeeppatidar30** [jhildenbiddle/css-vars-ponyfill#148]
<img width="727" alt="css-var-issue" src="https://user-images.githubusercontent.com/31273891/100200130-3043a600-2f24-11eb-9fdd-5dc38e8f3f65.png">

When we update href of link tag, it does not update DOM with latest styles because of disabled attribute added on link tag and when i remove disabled attribute using (linkElement.removeAttribute('disabled')) api it update the DOM with new styles but take some time to render the change on DOM. I can clearly see the performance issue.

**Comment by mrksmts** [comment]
+1 - We are seeing the same issue here.

**Comment by jhildenbiddle** [comment]
Happy to help, but I want to make sure I understand the issue(s). Based on the descriptions, it sounds like @sandeeppatidar30 may have a question/concern regarding performance while @mrksmts has identified a regression.

Can you each create a demo on https://codesandbox.io (or similar service) with relevant CSS? This will help me troubleshoot the issue and better understand your concerns.

Thanks!

**Comment by jhildenbiddle** [comment]
Issue confirmed in 2.4.x using this demo: https://css-vars-ponyfill-149.glitch.me/

Initial testing shows only IE11 is affected (modern browsers with `onlyLegacy:false` work as expected). Must be related to to the following change in 2.4.0:

> * Fix skip behavior of `<link>` elements with disabled attribute

Thanks for filing the issue. I'll look into this as soon as possible.
