### ISSUE TITLE
cssVars(): CSS parse error: property missing ':'

### ISSUE THREAD

**Issue by shivamssh** [jhildenbiddle/css-vars-ponyfill#151]
IE 11 when it loads the IE gives errors **"cssVars(): CSS parse error: property missing ':' " more than one time.**

I have applied :

```
cssVars({
  onlyLegacy: true,
  shadowDOM: true,
  watch: true,
  updateURLs: true,
  updateDOM: true,
  preserveVars: true
});
```

in polyfills and before that  installed **npm install css-vars-ponyfill** and imported as well **import cssVars from 'css-vars-ponyfill';**

**Ponyfill version - css-vars-ponyfill@2.4.2**

**Comment by jhildenbiddle** [comment]
Hi @shivamssh.

Please create a demo on https://codesandbox.io (or similar service) to demonstrate the problem. Without this, there simply isn't enough information in your description to provide assistance.

Thanks!

**Comment by jhildenbiddle** [comment]
Closing to to inactivity. Happy to reopen if/when a demo is made available for further investigation.
