### ISSUE TITLE
Looking for a way to pull the variable value via js

### ISSUE THREAD

**Issue by efraimbart** [jhildenbiddle/css-vars-ponyfill#152]
Equivalent to `getComputedStyle(document.documentElement).getPropertyValue('--variable');`

**Comment by jhildenbiddle** [comment]
@efraimbart --

Custom property values are available via the `cssVariables` argument in the `onComplete()` callback. See the [documentation](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=oncomplete) for details.

```js
cssVars({
  onComplete: function(cssText, styleElms, cssVariables, benchmark) {
    console.log(cssVariables);
  }
});
```

**Comment by efraimbart** [comment]
Thanks!
