### ISSUE TITLE
'[object NodeList]' is not a valid argument for 'Function.prototype.apply'

### ISSUE THREAD

**Issue by bbuhler** [jhildenbiddle/css-vars-ponyfill#153]
Hello (:

First of all thank you for your great work!

In our Sentry we see an exception connected to your library so I am posting it here:

```
'[object NodeList]' is not a valid argument for 'Function.prototype.apply' (evaluating 'a.rootElement.querySelectorAll('[data-cssvars="out"]')')
```

```
second argument to Function.prototype.apply must be an array (https://cdnjs.cloudflare.com/ajax/libs/css-vars-ponyfill/2.4.3/css-vars-ponyfill.min.js#8)
```

It appears mainly on Firefox (24) and (Mobile) Safari.

Cheers,
Ben

**Comment by tiperes** [comment]
Same here when trying to use with wkhtmltopdf... :(

**Comment by tiperes** [comment]
I have overcome the issue by wrapping all query selectors with Array.prototype.slice.call.
Example: 
Array.apply(null,Array.prototype.slice.call(o.rootElement.querySelectorAll('[data-cssvars]:not([data-cssvars="out"])')))

**Comment by jhildenbiddle** [comment]
Based on query selector in @bbuhler's error message and @tiperes' proposed fix, it looks like you both might be experiencing the same issue but at different points in the code:

@bbuhler:

https://github.com/jhildenbiddle/css-vars-ponyfill/blob/f37215c2c072b6a5695f08bf5d91898cb3640216/src/index.js#L278

@tiperes:

https://github.com/jhildenbiddle/css-vars-ponyfill/blob/f37215c2c072b6a5695f08bf5d91898cb3640216/src/index.js#L244

This feels like a similar to #144, which is to say the code above works fine but perhaps there is some app- or framework-specific condition that can cause the `rootElement` or the node list returned from the `querySelectorAll()` method to become invalid while the pony fill is doing its work. Who knows.

I have created a branch with the fix mentioned above: https://github.com/jhildenbiddle/css-vars-ponyfill/tree/fix-153. Checkout that branch, build, then test your preferred version in `/dist`. If this fixes your issue I'll publish a patch release. If you see other errors in Sentry, let me know and we'll continue trying to resolve the issues.

**Comment by jhildenbiddle** [comment]
@bbuhler @tiperes Ping!

**Comment by bbuhler** [comment]
Hi @jhildenbiddle,
I didn't had the chance to reproduce and test your branch yet. I tried using Firefox 24 via Browserstack, but unfortunately the VM browser always became unresponsive and ultimately crashed.

I will give it another try next week.

**Comment by bbuhler** [comment]
Hi @jhildenbiddle,
I was not able to reproduce the issue in a real browser. But as @tiperes mentioned it is reproducible with wkhtmltopdf CLI tool, so I tried with that and it looks like your changes resolves the issue.

Thank you (:
