### ISSUE TITLE
Not working IE11 in Prod Mode

### ISSUE THREAD

**Issue by sabariajith** [jhildenbiddle/css-vars-ponyfill#156]
css vars working fine in IE11 when run the application in local.
But when we host the application, then css vars not working.

I added following code in main.ts
cssVars({
    include: 'style',
   onlyLegacy: false,
  watch: true
});

**Comment by jhildenbiddle** [comment]
Hi @sabariajith --

I can't offer much assistance without additional details about your app. If I had to guess, I'd assume this is an Angular app or you are using a CSS-in-JS library that leverages [CSSOM APIs](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) in production. These topics and proposed solutions can be found here: #19, #23, #77.

Hope this helps. If not, let me know and we'll figure out the next steps.

**Comment by sabariajith** [comment]
Hi @jhildenbiddle 
The above mentioned solutions are not working in my case.  (Angular8 Project)
Actually the issue is in only material UI.
The css vars are not updating only material ui styles. 
Basically I am using another libs in my project. that libs also using material ui.
Is oncomplete or updateDom is necessary for legacy browsers.

**Comment by jhildenbiddle** [comment]
@sabariajith --

Best thing to do is create a demo on https://codesandbox.io/ that we can both work from. Otherwise, there just isn't enough information available for me to help you with your issue.
