### ISSUE TITLE
How to switch themes without browser reload using css variables?

### ISSUE THREAD

**Issue by Kevinjn0123** [jhildenbiddle/css-vars-ponyfill#157]
How to switch themes without browser reload using css variables

`

const themes = {
  light: {
    color: "green"
  },
  dark: {
    color: "blue"
  }
};

if (document.documentElement.hasAttribute("data-force-color-mode", "light")) {
cssVars({
   variables: themes.light,
});
}

if (document.documentElement.hasAttribute("data-force-color-mode", "dark")) {
  cssVars({
    variables: themes.dark,
  });
}`

Please help

**Comment by jhildenbiddle** [comment]
You've got the right idea.

**HTML**

```html
<html data-force-color-mode="light">
```

**CSS**

```css
body {
  background-color: var(--color);
}
```

**JS**

```js
const themes = {
  light: {
    color: "green"
  },
  dark: {
    color: "blue"
  }
};
const forceColorMode = document.documentElement.getAttribute("data-force-color-mode")

cssVars({
  variables: themes[forceColorMode],
});
```

For more details, see the [`options.variables`](https://jhildenbiddle.github.io/css-vars-ponyfill/#/?id=variables) section of the docs.

Hope this helps!

**Comment by jhildenbiddle** [comment]
@Kevinjn0123 --

You haven't specified *how* you want to trigger the theme switch. Here's a quick demo with one way to do it: 

https://codesandbox.io/s/css-vars-ponyfill-157-jdng3
