### ISSUE TITLE
`CSS.supports()` doesn't support in IE11, but css-vars-ponyfill insert it into build artifact.

### ISSUE THREAD

**Issue by nukopy** [jhildenbiddle/css-vars-ponyfill#159]
Hi, thanks for the good package css-vars-ponyfill.

When using css-vars-ponyfill, I faced IE11 compatible error like below. Can't I use css-vars-ponyfill in IE11?

## What I wanna do

I wanna use CSS variables in IE11.

## Problems

When I build JavaScript code that contains css-vars-ponyfill code, my build contains `CSS.supports()`. However, `CSS.supports()` is not suported in IE11.

Is there anyone who solve this problem?

**Comment by jhildenbiddle** [comment]
Hi @nukopy.

Yes, the ponyfill works in IE11. It wouldn't be of much use if it didn't. 😉 

Links to the [documentation](https://jhildenbiddle.github.io/css-vars-ponyfill) and a [demo](https://codepen.io/jhildenbiddle/pen/ZxYJrR/) are available in the repo's [README.md](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/README.md). All of the information you need can be found there. If you need more assistance, you'll need to provide specifics on your project such as how you're using the ponyfill and which build tools (if any) you are using.

FWIW, the ponyfill has nothing to do with the `CSS.supports()` method mentioned above. That is a native method found only in modern browsers: https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports
