### ISSUE TITLE
`fixKeyframes` throws error when using shadow DOM + legacy browsers

### ISSUE THREAD

**Issue by mijelin** [jhildenbiddle/css-vars-ponyfill#171]
When using web components / shadow DOM:
```js
cssVars({
  rootElement: document.querySelector('custom-element').shadowRoot,
  onlyLegacy: false,
  variables: { /* ... */ }
});

// or
// cssVars({
//   rootElement: document.querySelector('custom-element'),
//   shadowDOM: true,
//   onlyLegacy: false,
//   variables: { /* ... */ }
// });
```

and the parsed styles contain keyframes rules, an error is thrown when performing the DOM update:
```
e.getElementsByTagName is not a function
```

@ https://github.com/jhildenbiddle/css-vars-ponyfill/blob/v2.4.7/src/index.js#L837

Reproduction: https://stackblitz.com/edit/typescript-xeedun?file=index.ts

**Comment by jhildenbiddle** [comment]
Fixed in 2.4.8
