### ISSUE TITLE
map file

### ISSUE THREAD

**Issue by oivinds** [jhildenbiddle/css-vars-ponyfill#173]
Chrome complains about a missing map file. Im loading the package from https://cdn.jsdelivr.net/npm/css-vars-ponyfill called from wp_register_script() a Wordpress PHP method. Maybe I should just suppress it from chrome dev tools?

**Comment by jhildenbiddle** [comment]
This error occurs when you link to the CDN alias URL as specified in the docs:

```html
<script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"></script>
```

The error is harmless, but if you would like to prevent it from showing up in your console you can link directly to the file of your choice in the [dist](https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2.4.8/dist/) directory:

```html
<script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2/dist/css-vars-ponyfill.min.js"></script>
```
