### ISSUE TITLE
cssVars():: CSS parse error: missing '}'

### ISSUE THREAD

**Issue by kmanasa16** [jhildenbiddle/css-vars-ponyfill#174]
Facing cssVars() parse error in Samsung 2017 TV that uses chromium browser

**These are my current versions:**
Chromium browser: v47
Svelte: 3.55.0
Tailwind: 3.2.4
Samsung 2017TV: Tizen-3
css-vars-ponyfill: 2.4.8"

**Code base:**
cssVars({
		variables: {
			'--tw-space-x-reverse': '0',
			'--tw-space-y-reverse': '0',
			'--tw-translate-x': '0',
			'--tw-translate-y': '0',
			'--tw-rotate': '0',
			'--tw-skew-x': '0',
			'--tw-skew-y': '0',
			'--tw-scale-x': '1',
			'--tw-scale-y': '1',
			'--tw-text-opacity': '1',
			'--tw-bg-opacity': '1',
			'--tw-gradient-stops': 'var(--tw-gradient-from), var(--tw-gradient-to)',
			'--tw-ring-color': 'rgba(59,130,246,0.5)',
			'--tw-divide-opacity': '1',
			'--tw-border-opacity': '1',
			'--tw-gradient-from': 'var(--main-background)',
			'--tw-aspect-h': '9',
			'--tw-aspect-w': '16',
			'--tw-ordinal': '0',
			'--tw-slashed-zero': '0',
			'--tw-numeric-figure': '0',
			'--tw-numeric-spacing': '0',
			'--tw-numeric-fraction': '0',
			'--tw-ring-inset': '0',
			'--tw-ring-offset-width': '0px',
			'--tw-ring-offset-color': '#fff',
			'--tw-ring-offset-shadow': '0 0 #0000',
			'--tw-ring-shadow': '0 0 #0000',
			'--tw-shadow': '0 0 #0000',
			'--tw-shadow-colored': '0 0 #0000',
			'--tw-blur': '0',
			'--tw-brightness': '0',
			'--tw-contrast': '0',
			'--tw-grayscale': '0',
			'--tw-hue-rotate': '0',
			'--tw-invert': '0',
			'--tw-saturate': '0',
			'--tw-sepia': '0',
			'--tw-drop-shadow': '0',
			'--tw-backdrop-blur': '0',
			'--tw-backdrop-brightness': '0',
			'--tw-backdrop-contrast': '0',
			'--tw-backdrop-grayscale': '0',
			'--tw-backdrop-hue-rotate': '0',
			'--tw-backdrop-invert': '0',
			'--tw-backdrop-opacity': '0',
			'--tw-backdrop-saturate': '0',
			'--tw-backdrop-sepia': '0',
			'--tw-gradient-to': 'transparent',
			'--tw-placeholder-opacity': '1',
			'--mask-image-content':
				'linear-gradient(to bottom,transparent,black 10%,black 90%,transparent)',
			'--mask-image-scrollbar': 'linear-gradient(black, black)',
			'--mask-size-scrollbar': '0% 100%',
			'--mask-size-content': '100% 100%',
			'--star-size': '30px',
			'--star-color': '#b4bace',
			'--star-background': '#fed15c',
		},
	});
![Css parse error](https://github.com/jhildenbiddle/css-vars-ponyfill/assets/42050051/b0412c21-cc53-42cd-89d3-fbc92e12de2f)

**Can someone help me for a solution please.**

**Comment by jhildenbiddle** [comment]
@kmanasa16 -- 

The error is self-explanatory if correct: one of your stylesheets is missing a closing `}` which is causing the CSS parser to fail. The error message is providing a reference to the `<link>` element that it believes contains the error. If that linked stylesheet does not contain the error, you may want to check the stylesheet coming immediately before or after it.

Closing as resolved for now since this appears to be an issue with your stylesheet(s).
