### ISSUE TITLE
ie 9 10 Use without effect

### ISSUE THREAD

**Issue by G1King** [jhildenbiddle/css-vars-ponyfill#175]
ie 9 10 Use without effect

**Comment by jhildenbiddle** [comment]
@G1King --

I don't know what this means. Are you saying the library does not work properly in IE9 and IE10?

**Comment by G1King** [comment]
> @G1King --
> 
> I don't know what this means. Are you saying the library does not work properly in IE9 and IE10?

This library has no effect on ie9 10 when using cssvars the color display is blank

**Comment by jhildenbiddle** [comment]
Verified that the library is working fine on IE9.

Markup:

```html
<!doctype html>
<html lang="en">

<head>
    <style>
        :root {
            --background: red;
            --color: white;
        }

        body {
            background-color: var(--background);
            color: var(--color);
        }
    </style>

    <script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"></script>
    <script>
        cssVars({
            // Options...
        });
    </script>
</head>

<body>
    <p>This is a test</p>
</body>
</html>
```

Result:

![](https://github.com/jhildenbiddle/css-vars-ponyfill/assets/442527/194b49c4-e8c4-4d3f-bb6a-f75526d69e95)
