### ISSUE TITLE
Add the library only if the browser doens't support css-vars

### ISSUE THREAD

**Issue by tristanbes** [jhildenbiddle/css-vars-ponyfill#21]
Do you see any objection, in order to avoid loading the script, in doing this ? 

```html
<body>
    ....

    <script>
      <!-- Add ponyfill for css variables on legacy browsers -->
      function browserCanUseCssVariables() {
        return window.CSS && window.CSS.supports && window.CSS.supports('--fake-var', 0);
      }

      if (!browserCanUseCssVariables()) {
        var imported = document.createElement('script');
        imported.src = 'js/css-vars-ponyfill.min.js';
        document.head.appendChild(imported);
        cssVars();
      }
    </script>
</body>
```

**Comment by jhildenbiddle** [comment]
You certainly can do that if you want to avoid the additional network request in modern browsers. 

One thing to keep in mind: if you intend to change CSS custom property values dynamically on the client, the ponyfill's [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsvariables) features will make life easier by providing a single interface for applying changes in both modern and legacy browsers (see the docs for details). If this is the case, you'll need to include the ponyfill in modern browsers as well.

**Comment by tristanbes** [comment]
Ok thanks for your answer :-)
