### ISSUE TITLE
Add tags to generate release

### ISSUE THREAD

**Issue by 42antoine** [jhildenbiddle/css-vars-ponyfill#25]
Could you please add tags to fix release in time ?

**Comment by jhildenbiddle** [comment]
Done. I will push tags in future releases as well.

For a list of changes for each release, please see the [CHANGELOG.md](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/CHANGELOG.md).

**Comment by 42antoine** [comment]
Awesome, Thanks !
