### ISSUE TITLE
SCRIPT5: Access is Denied on IE10 and 11 when using file protocol

### ISSUE THREAD

**Issue by jkosecki** [jhildenbiddle/css-vars-ponyfill#3]
Hi, 
I was testing your ponyfill on VirtualBox with IE10 and 11 and I've noticed, that if a website is opened using file protocol, the script won't work because of the "SCRIPT5: Access is denied" error.

My HTML has a very simple structure, the `<head>` tag content is:
```
<link rel="stylesheet" href="main.css">
<script src="css-vars-ponyfill/dist/css-vars-ponyfill.js"></script>
<script>cssVars()</script>
```
The script then creates `XMLHttpRequest` and tries to fetch it in line 68: `xhr.open("GET" url)`, which in this case is `xhr.open("GET", "main.css")` and fails with the error above.

It seems that the problem concerns only file protocol. When I've served the same page via HTTP from my host, everything worked when opened with IE11 on the guest machine.

**Comment by jhildenbiddle** [comment]
Hi @jkosecki .

What you are experiencing is a security restriction enforced by the browser. It is not a limitation of the ponyfill.

It is possible to get around this limitation if your browser provides an option to disable this security restriction. For example, Chrome provides a `--allow-file-access-from-files` command line switch that will allow `file://` URIs to read other `file://` URIs. Other browsers may offer similar workarounds.

Hope this helps!
