### ISSUE TITLE
Demo doesn't work on IE11

### ISSUE THREAD

**Issue by missmatsuko** [jhildenbiddle/css-vars-ponyfill#30]
Looking at browser support for CSS vars, the biggest browser that doesn't support it is IE11:
https://caniuse.com/#feat=css-variables

CodePen doesn't work at all on IE11, so I can't easily see how the code in the demo works for a browser that doesn't natively support CSS Variables.

**Comment by jhildenbiddle** [comment]
Hi @missmatsuko.

Finding online dev environments that still support IE11 is tough. To work around this, the CodePen demo calls the ponyfill with the [`onlyLegecy`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsonlylegacy) option set to `false`. This tells the ponyfill to do its thing regardless of whether or not the browser has native support for CSS custom properties. You can view the CodePen demo with Chrome/Edge/Firefox/Safari/Vivaldi, changes settings as much as you like, and the results will be the same as if the demo was run in a legacy browser like IE11.

If you want to test the ponyfill in a CodePen-like environment with IE11, the only option I know of is [JSBin](https://jsbin.com/). It still supports IE11, but I wouldn't bet on that being the case forever.

To save you some time, I recreated the CodePen demo in JSBin.

* https://jsbin.com/qujobof/edit?css,js,output
