### ISSUE TITLE
IE11 fails to render if I don't delay a certain amount before processing

### ISSUE THREAD

**Issue by mcblum** [jhildenbiddle/css-vars-ponyfill#36]
Hey! 

So I ran into a new thing, and I'm wondering if you have any ideas. I was seeing most elements completely unstyled, but a few were, so the lib was working as expected. I added a `setTimeout` with a delay of 2,500 ms and everything worked perfectly. Can you think of any reason why adding the delay would cause all elements to be styled? Does it potentially relate to the browser not having rendered the entire DOM yet?

Thank you!
Matt

**Comment by acicali** [comment]
Might the script be loading before all of the styles are available?

**Comment by jhildenbiddle** [comment]
@mcblum,

Check out #29.

If you're still having trouble, let me know and hopefully I'll be able to help. The fastest way to pinpoint the issue is to create a demo on https://codesandbox.io/ or https://stackblitz.com/ that we can both use for reference.

**Comment by jhildenbiddle** [comment]
Hey @mcblum.

Checking in to see if you're issue it resolved. If so, I will close this issue. If not, I'm happy to lend a hand where I can.

**Comment by mcblum** [comment]
@jhildenbiddle sorry! We're all good so I'm closing it. My fault for not making sure the issue was closed.

**Comment by jhildenbiddle** [comment]
@mcblum -- no worries at all. My GitHub issue OCD is real. 😉
