### ISSUE TITLE
Add Edge 15 to legacy browsers

### ISSUE THREAD

**Issue by theDyingMountain** [jhildenbiddle/css-vars-ponyfill#41]
If _onlyLegacy_ property is set to `true`, the script will not run on Microsoft Edge 15.
So in my case i have to set the property false, to show my website correctly on edge 15.
Edge 15 has issues rendering css vars: see [https://caniuse.com/#search=css%20var](https://caniuse.com/#search=css%20var)

**Comment by jhildenbiddle** [comment]
Hi @theDyingMountain.

The ponyfill cannot assume when it is safe to override a browser's native CSS custom property implementation. Fortunately, you can tell the ponyfill when it is appropriate using [`options.onlyLegacy`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsonlylegacy) and basic browser detection:

```javascript
cssVars({
  // Treat Edge 15/16 as legacy
  onlyLegacy: !(/Edge\/15|Edge\/16./i.test(navigator.userAgent)),
});
```

Hope this helps.

**Comment by theDyingMountain** [comment]
Okay thx for this information
