### ISSUE TITLE
How to use css variable from CDN file in angular 6?

### ISSUE THREAD

**Issue by sga-girdhari** [jhildenbiddle/css-vars-ponyfill#46]
Hi @jhildenbiddle ,

I am trying to use this library in one of my angular 6 project, which is using CSS variable from a file coming from CDN (due to theme implementation, I can switch theme/files dynamically).

But I am getting CORS issue on IE, and warning on chrome/other browsers regarding undefined variable (I will set onlyLegacy to true though).

Can you please help me, in loading file from CDN on angular 6 project.

Please see attached snapshot.
![image](https://user-images.githubusercontent.com/28899525/50097088-1e88fc80-023f-11e9-8c0b-421b39b72583.png)

Thanks.

**Comment by jhildenbiddle** [comment]
Hi @sga-girdhari,

The errors you are receiving indicate that the CDN server you are using is not [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)-enabled. Specifically, the CDN server is not setting the appropriate response headers that allow the ponyfill to request `<link>` stylesheets via XMLHttpRequest (aka "AJAX"). This is required in order for the ponyfill to work, as it is the only way the ponyfill can read the CSS content of the linked stylesheet.

If possible, switch to a CDN that is already CORS-enabled. If this is not possible, consider hosting the CSS file locally (on the same server as your app).

**Comment by sheikalthaf** [comment]
@sga-girdhari @jhildenbiddle Hi,

I'm planning to implement this ponyfill to angular 7 project. but it is only working for app.component file.
for other component it is not working. anything I'm missing here in angular project

**Comment by sga-girdhari** [comment]
Hi @sheikalthaf,
From where are you are calling `cssVars` method, I would suggest to do it from `main.ts` file. And it should work for you irrespective of your component (as per my understanding) variables are replaced on runtime.

Thanks.

**Comment by sheikalthaf** [comment]
@sga-girdhari Thanks. I have placed the `cssVars` in themeService in root.

```javascript
cssVars({
      rootElement: element,
      onlyLegacy: false,
      onlyVars: true,
      variables: theme.properties,
      watch: true,
      onComplete: (a, b, variables) => {}
    });
```

if i enable watch then styles get applied but IE browser hangs for a while and then restored.
how you handling this in your angular app?

**Comment by jhildenbiddle** [comment]
@sheikalthaf,

Best to create a new issue since this one is closed.

Before you do that, understand that I'm not sure how much help I can provide without seeing the CSS involved. Consider creating a demo project that is configured like yours so others can review and make suggestions. I have found [codesandbox.io](https://codesandbox.io/) and [stackblitz.com](https://stackblitz.com/) useful for such tasks.
