### ISSUE TITLE
Transform CSS without applying/rendering it to the DOM at all

### ISSUE THREAD

**Issue by CombeeMike** [jhildenbiddle/css-vars-ponyfill#48]
Is it possible to transform some CSS which I only have in memory without applying it to a `style` element in the DOM first?

Something like this:

```js
const css = `
  :root {
    --main-color: blue;
  }

  .some-class {
    color: var(--main-color);
  }
`;

cssVars({
  include: css, // I guess, this is not working. Is there some alternate way?
  onlyLegacy: false,
  onComplete(cssText, styleNode, cssVariables) {
    // Apply the transformed cssText on my own...
  }
});
```

This is not happening on the server but on the client.

**Comment by jhildenbiddle** [comment]
Hi @CombeeMike,

The ponyfill currently does not support this, but you are welcome to use the `transform-css.js` module used internally by the ponyfill to do exactly what you're looking for.

https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/src/transform-css.js

Just import the module, then call the `transformVars()` function with options set as needed. See the source comments for details.

```javascript
import transformCss from 'path/to/node_modules/css-vars-ponyfill/src/transform-css';

const cssText = `
  :root { --color: red; }
  body { color: var(--color); }
`;

const cssOut = transformCss(cssText, { /* Options */ });
```

The other option is:

1. Append a new `<style>` element to the DOM with a unique ID and your CSS

   ```javascript
   const styleElm = document.createElement('style');
   styleElm.id = 'my-unique-id';
   styleElm.textContent = cssText;
   document.body.appendChild(styleElm);
   ```

1. Call the ponyfill with the following options:

   ```javascript
   cssVars({
     include: '#my-unique-id',
     updateDOM: false
     onSuccess(cssText, node, url) {
       node.parentNode.removeChild(node);
     })
   });
   ```

The second option is not as clean as the first, but it allows you to use the ponyfill as-is with all of its features.

Hope this helps!

**Comment by CombeeMike** [comment]
Thank you for the info! I'll look into it and will get back to you if something is still unclear ;)

**Comment by jhildenbiddle** [comment]
You bet, @CombeeMike. Let me know how it goes. I'll leave the issue open until then.
