### ISSUE TITLE
variable scanning

### ISSUE THREAD

**Issue by alias** [jhildenbiddle/css-vars-ponyfill#50]
pls be more robust when it comes to variable detection. I had some declarations like
`var( --myvariable)`
and the space in fron was taken seriously (an appropriate warning was shown).

Thx!

**Comment by jhildenbiddle** [comment]
This issue has been fixed and will be available in upcoming 1.16.3. 

Thanks for the heads up, @alias.

**Comment by jhildenbiddle** [comment]
@alias --

1.16.3 has been release. Just a heads up. 😄
