### ISSUE TITLE
css-vars-ponyfill doesn't work when variables are set through inline style attribute

### ISSUE THREAD

**Issue by CthulhuDev** [jhildenbiddle/css-vars-ponyfill#51]
Title says it all.

I'd like to use this ponyfill to work with splitting.js.org in an ie11 environment but the ponyfill doesn't scan for inline css variables.

**Comment by jhildenbiddle** [comment]
Hi @CthulhuDev,

This has been covered in #12 and #26. An explanation of the challenges involved is available [here](https://github.com/jhildenbiddle/css-vars-ponyfill/issues/26#issuecomment-425682507).

Sorry I can't provide a more encouraging reply. Best of luck with splitting.js!

**Comment by CthulhuDev** [comment]
Thanks for the reply, I swear I used the issue search before issuing another thread :sweat_smile: 
Sorry for bothering you, have a nice day and thanks for the reply!

**Comment by jhildenbiddle** [comment]
No bother at all. I appreciate the interest! 😄
