### ISSUE TITLE
IE9 CORS check includes port In getURLS() -> urlArray.forEach()

### ISSUE THREAD

**Issue by BryonCLewis** [jhildenbiddle/css-vars-ponyfill#54]
First thanks for this wonderful piece of software.  Please remove this if it isn't an issue or I am misunderstanding something.

When using IE11 in IE9 mode it compares the parse.host and location.host to determine if it is a CORS request.  For some reason on IE9 the location.host includes the port number.

For example:
```
            var parser = document.createElement("a");
            parser.setAttribute("href", url);
            parser.href = String(parser.href);
            console.log("url:" + url);
            console.log("Parser.host: " + parser.host + " location.host: " + location.host);
            var isCrossDomain = parser.host !== location.host;
            var isIElte9 = document.all && !window.atob;
            console.log("parser.protocol: " + parser.protocol + " location.protocol: " + location.protocol);
            console.log("IsIElte9: " + isIElte9);
            isCrossDomain = false;
```
That will produce:
url:css/fonts.css
Parser.host: localhost:80 location.host: localhost
parser.protocol: http: location.protocol: http:
IsIElte9: true
url:js/2d_sim_case/EMR/VitalsDisplay/vitalsdisplay.css
Parser.host: localhost:80 location.host: localhost
parser.protocol: http: location.protocol: http:
IsIElte9: true

So they are on the same host but the inclusion of the port number is throwing off the IE9/CORS check and causing it to error out.  I've manually changed the isCrossDomain to false afterwards and it runs my website/app perfectly.  The difference in Port number occurs in IE 10,11 as well but not in Edge.  I don't have firefox or chrome forced to doing the conversion so I don't know.

I think either filtering out that port number when IE9 would fix this.

Just a couple of Updates to make it clearer:  Testing on a website, not just on a local xampp server it does the same thing, comparing a hostname with port number to one without.

**Comment by BryonCLewis** [comment]
Awesome.  Just tested on localhost and remote using IE11 in IE9 document mode and it worked perfectly.  Then fired up the MS IE9 Virtual Machine and tested in true IE9, worked perfectly as well.  Your change looks quite similar to what I did to temporarily get it to work.  IE is forever going to be a pain.  Thanks again.

**Comment by jhildenbiddle** [comment]
Good to hear.

Version 1.16.4 has been published to NPM with the fix. The "54" branch will be deleted, so be sure to update your package.json with the latest npm version instead of the git repo branch.

Thanks again, @BryonCLewis.
