### ISSUE TITLE
ios8 window.performance is undefined

### ISSUE THREAD

**Issue by LYnnProspery** [jhildenbiddle/css-vars-ponyfill#60]
ios8 window.performance is undefined
so it will throw an exception
hopes to fix it by and performance property check:

`return isBrowser && window.performance && window.performance.now ? performance.now() : new Date().getTime();`

**Comment by jhildenbiddle** [comment]
Fixed in 1.17.2.

Sorry about that, @LYnnProspery. I added the the `benchmark` argument to `options.onComplete` and neglected to write a test for it.
