### ISSUE TITLE
double styles in chrome dev tool

### ISSUE THREAD

**Issue by neilrogers** [jhildenbiddle/css-vars-ponyfill#61]
really surprised i cannot find any information about this anywhere.

I'm including the pony fill like this

```
<link rel="stylesheet" href="/assets/css/style.css" type="text/css">
<script src="/assets/js/css-vars-ponyfill.min.js"></script>

stylesheet looks something like this

:root {
    --blue: #00AEEF;
    --grey: #808080;
    --orange: #F78D2A;
    --yellow: #FFC400;
}
/* UTILITY */
/* ------------------------------------- */
.blue {
    color: var(--blue);
}
```
In chrome dev tools I see 2 lots of styles
<img width="480" alt="screen shot 2019-03-07 at 7 22 44 pm" src="https://user-images.githubusercontent.com/839107/53945933-716fa300-410e-11e9-995c-d15900cc6400.png">

**Comment by jhildenbiddle** [comment]
This is expected.

When you add a stylesheet via a `<link>` or `<style>` tag:

```html
<style>
  :root {
    --color: red;
  }

  p {
    color: var(--color);
  }
</style>
```

The ponyfill processes this CSS, then appends a new `<style>`tag to the DOM. The end result is that two `<style>` tags now exist, with the second one overriding the first.

```html
/* Your CSS */
<style>
  :root {
    --color: red;
  }

  p {
    color: var(--color);
  }
</style>
/* Ponyfill-generated CSS */
<style>
  p {
    color: red;
  }
</style>
```

What you're seeing in the dev tools are both your original styles (the ones that are crossed out) and the ponyfill-generated styles (which override the original styles, causing them to be crossed out).

**Comment by neilrogers** [comment]
thanks very much.

but chrome supports the css variables why not check the browser and pony fill or not? I know i can check but would of thought pony fill would be smart enough.

No one else cares they have double styles in chrome and it slowing down the browser?

**Comment by jhildenbiddle** [comment]
It sounds like you've set [`options.onlyLegacy`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsonlylegacy) to `true`. From the README:

> When true, the ponyfill will only transform custom properties, generate CSS, and trigger callbacks in legacy browsers that lack native support. When false, the ponyfill will treat all browsers as legacy, regardless of their support for CSS custom properties.

You'll want to set this option to `false` in production, but you'll see this set to `true` in demos (like the linked [CodePen demo](https://codepen.io/jhildenbiddle/pen/ZxYJrR/) in the README) and automated tests which allows ponyfill behavior and output to be checked without requiring a legacy browser like IE11.

Try removing or commenting out the `onlyLegacy: false,` line in the "JS" panel of the [CodePen demo](https://codepen.io/jhildenbiddle/pen/ZxYJrR/) to see what I mean.
