### ISSUE TITLE
Lazy-load or conditional load

### ISSUE THREAD

**Issue by Zireael** [jhildenbiddle/css-vars-ponyfill#64]
Hi, 
I'm trying to limit loading Ponyfill chunk (after splitting the code with Webpack) only if browser is IE11. 
Something like this:

```
if (!!window.MSInputMethodContext && !!document.documentMode) { // IE11 detect
  require(/* webpackChunkName: "css-vars-ponyfill" */ "css-vars-ponyfill");
  // or 
  () => import(/* webpackChunkName: "css-vars-ponyfill" */ "css-vars-ponyfill")
}

```
Problem is, I can't figure out how to call the main function to initialize, since I'm not assigning it a name and it isn't registered under `window.cssVars()`

This way loads the package even tho I won't be using it in all browsers:
```
// this named import can't be put inside conditional statement, as needs to be in the 'root' of code
import cssVars from 'css-vars-ponyfill';
// Call using defaults
cssVars();
```
I'd appreciate your advice on how to limit my package download size to only when polyfill is needed.

**Comment by jhildenbiddle** [comment]
Hi @Zireael.

I think you're looking for [dynamic imports](http://2ality.com/2017/01/import-operator.html):

```js
const hasNativeSupport = ((window || {}).CSS || {}).supports && window.CSS.supports('(--a: 0)');

if (!hasNativeSupport) {
  import("path/to/css-vars-ponyfill.js")
  .then(cssVars => {
    cssVars();
  });
}
```

According to the [webpack docs](https://webpack.js.org/guides/lazy-loading/):

> Note that when using import() on ES6 modules you must reference the .default property as it's the actual module object that will be returned when the promise is resolved.

```js
const hasNativeSupport = ((window || {}).CSS || {}).supports && window.CSS.supports('(--a: 0)');

if (!hasNativeSupport) {
  import(/* webpackChunkName: "css-vars-ponyfill" */ "cssVars").then(module => {
    const cssVars = module.default;
    cssVars();
  });
}
```

One thing worth considering: if you plan on changing CSS custom property values via JavaScript, you should do so via the ponyfill's [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsvariables) feature as this provides a single interface for updating both modern and legacy browsers.

```js
cssVars({
  variables: {
    "--my-color": "blue"
  }
});
```

Hope this helps!

**Comment by Zireael** [comment]
Perfect example, thank you! I'll try it out in a bit later. Yes, I was actually planning on using JS to update the variables and I saw it's done through your options.variables

If I may suggest, would you consider adding this import example to your documentation? It is very neat and I'm sure it would come handy to some folk. I realise Webpack is just one of few packagers out there (there's Parcel too and others, I believe?), but it would give people an idea how to make their package size dynamic. I plan to make another simple conditional where if --var is natively supported, I modify them directly, if --var is not supported, I'd load Ponyfill and route the modification through Ponyfill.

A side question: if I want to modify --var with JS (=> `options.variables{}`), would I need to ensure to keep `options.preserve` as 'true', correct?

**Comment by jhildenbiddle** [comment]
Glad it was helpful. 😄 

As far as adding the example to the official docs, I'm hesitant to do so because that becomes a slippery slope towards adding implementation examples for Gulp, Grunt, Rollup, React, Vue, Angular, etc. and "the example in your docs doesn't work for me!" issues here on GitHub. I'd rather people read the docs of the bundler/library/framework in question instead of a doing a blind copy/paste from this repo's README. 

Regarding the use of [`options.preserve`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionspreserve), you only need to set this option to `true` if you want the original CSS declarations (e.g. `--color: red`) and values (e.g. `var(--color)`) to be included in the transformed CSS output. I think what you're interested in is [`options.updateDOM`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsupdatedom), which you would want to set to `true` (default) so that new values are applied to the DOM (instead of just the `cssText` argument of the `onComplete` callback).

**Comment by standerksen** [comment]
Hi @jhildenbiddle,

Sorry for bumping a closed thread, but I am having a really hard time getting css-vars-ponyfill to work using Gulp. I know that you said you do not feel like writing documentation for different bundlers but I still hope you can help me out.

I am not sure if I should be using cssVars in the gulpfile.js or in the regular JavaScript. In the regular JavaScript I keep getting the error that cssVars is not found. I have tried many different ways of including it in gulpfile.js. Unfortunately I am not really sure what I should be doing.

I've included it in gulpfile.js using `const ponyfill = require('css-vars-ponyfill');` but I am not sure where to go from there.

Things I've tried:
- Adding it to the regular pipeline by adding `gulp.pipe(ponyfill)`
- Defining a new function `function pf() { return ponyfill('cssVars'); }` and including that in the export with `export.default = pf;`
- Just leaving the require and trying to call `cssVars ({ ... });` in the regular JavaScript, which results in 'cssVars not found'

None of the things I am trying seems to be working. I hope you can help me in the right direction while I keep fiddling with it.

Thanks in advance.

**Comment by jhildenbiddle** [comment]
@standerksen --

Happy to help. Can you create a new issue so we can track this separately?

Thanks!

**Comment by standerksen** [comment]
Actually I have already figured it out with the help of a colleague. I just needed to install Ponyfill using npm install and then include the plain .js file which is installed in Gulp under `paths = { js: ['<path>'] }`.
