### ISSUE TITLE
Force support for Edge 15

### ISSUE THREAD

**Issue by warrebuysse** [jhildenbiddle/css-vars-ponyfill#65]
Normally Edge 15 should work with CSS variables (like 13-14-16-17 and 18 does), but there are quite a lot of problems with it, and Microsoft is not fixing them. Is there a way to force
`cssVars()` on a specific browser (edge 15.x)?

**Comment by jhildenbiddle** [comment]
Hey @warrebuysse.

There is indeed: https://github.com/jhildenbiddle/css-vars-ponyfill#optionsonlylegacy

```js
cssVars({
  // Treat Edge 15/16 as legacy
  onlyLegacy: !(/Edge\/1[56]\./i.test(navigator.userAgent))
});
```

Edge 16 also has issues which is why it is included in the test.

**Comment by wannesdebacker** [comment]
@jhildenbiddle cheers mate!
