### ISSUE TITLE
Not working in IE10

### ISSUE THREAD

**Issue by Aixoniarutad** [jhildenbiddle/css-vars-ponyfill#67]
The polyfill docs say IE9+ is supported, but it doesn't seem to be working on IE10. IE11 works fine. I'll post an example below. Can someone let me know if I'm doing something wrong or missing anything? Thanks!

Doesn't seem possible to view a JSFiddle or CodePen using IE. So follow the steps below to recreate the issue.

1. Open IE
2. Go to https://htmledit.squarefree.com/
3. Open dev-tools and emulate IE10
4. Paste the following code

```
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@1"></script>

<script>
// Call the polyfill
cssVars()
</script>

<style>
:root {
  --color-red: red;
  --color-blue: blue;
}

.testing-red {
  color: var(--color-red)
}
.testing-blue {
  color: var(--color-blue)
}
</style>

</head>

<body>
    <div class="testing-red">Hello World - Red</div>
    <div class="testing-blue">Hello World - Blue</div>
</body>

</html>
```

**Comment by jhildenbiddle** [comment]
Hi @Aixoniarutad.

I'm not seeing any issue with IE10 using using the site and code you've provided above (see screenshot).

![ie10](https://user-images.githubusercontent.com/442527/55653220-b553d780-57a2-11e9-9be0-9fd45a54903a.png)

**Comment by Aixoniarutad** [comment]
Thanks for the quick response. To clarify, you're using actual IE10, not using IE11's dev-tools to emulate IE10?

**Comment by jhildenbiddle** [comment]
Correct. That's what the IE10 window was meant to communicate. 😄

**Comment by Aixoniarutad** [comment]
Awesome, thanks. You can close this!

**Comment by jhildenbiddle** [comment]
You bet.
