### ISSUE TITLE
[Feature request] Please add option to use XMLHttpRequest.withCredentials

### ISSUE THREAD

**Issue by amojicamu** [jhildenbiddle/css-vars-ponyfill#7]
Hello. Currently there is not way to specify that the style URL requests should pass credentials. This is needed when working with secured sites. In particular I need the request to include a server-set authentication cookie.

Let me know if this makes sense

**Comment by jhildenbiddle** [comment]
Just had another thought...

A better solution might be to add an `onBeforeSend` (or similarly named) callback that makes the [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) object available before each request is made. This way you could inspect the request URL, set properties or call methods on a per-request basis. This is also cleaner than adding multiple xhr-related options to the lib.

**Comment by amojicamu** [comment]
Thanks for your prompt answer. I have tried setting up withCredentials = true and it works as expected. The last option seems even better. Would provide a lot of flexibility. I wonder how something similar could be achieved while maintaining IE9 support (not that I need it, I looked at the code from get-css-data)

**Comment by jhildenbiddle** [comment]
Excellent. I'll add the callback to `get-css-data`, update the dependency for `css-vars-ponyfill`, then publish the update as 1.5.0 before EOW.

Sound good?

**Comment by amojicamu** [comment]
Yes. sounds great. I'll give it a try as soon as you have it. Thanks indeed

**Comment by amojicamu** [comment]
Yes. I tested 1.5.0 adding  `withCredentials = true` at the ` options.onBeforeSend` callback. It correctly passes the server-set cookie I needed. The request is authenticated on server. Thanks indeed.

**Comment by amojicamu** [comment]
Fast release cycle, nice. Yes I saw the issue, For the moment I only have absolute URLs, but should prove useful down the road. Thanks again for the fix
