### ISSUE TITLE
Not working in IE9 & IE10 if using syle-loader

### ISSUE THREAD

**Issue by AAAgeekWeb** [jhildenbiddle/css-vars-ponyfill#73]
if I use style-loader, the code will fail; if I don't use style-loader (separate css), the code will take effect
`{ test: /\.scss$/, use: [ 'style-loader', 'css-loader', 'sass-loader' ] }`

In IE9 and IE10, only the style tag appears, and the content inside is empty.
`<style type="text/css" data-cssvars="skip" data-cssvars-job="1"></style>`

To be sure, the project is invalid due to the style-loader!

**Comment by jhildenbiddle** [comment]
@AAAgeekWeb --

This is the same issue as #70. As I mentioned there:

> You will need to provide either access to your application or a test repo that demonstrates the issue in order for me to help.

If style-loader renders empty `<style>` elements, then it sounds like style-loader simply doesn't work with IE9/10. If this is the case, there is nothing to "fix" on the ponyfill side.
