### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'window.performance.now)

### ISSUE THREAD

**Issue by devbazilio** [jhildenbiddle/css-vars-ponyfill#76]
`(window.performance || {}).now`
if browser is ancient then **{}.now** causes error

**Comment by jhildenbiddle** [comment]
Confirmed. Thanks, @devbazilio. Will be fixed in the next version.

**Comment by jhildenbiddle** [comment]
@devbazilio --

What browser(s) did you have issues with? I see no issues with legacy browsers as far back as IE9 or Safari 6.2. If you're referring to truly ancient browsers like IE <= 8 and Safari <= 6.2 then... well, how much of a real-world issue is this given the number of users on those platforms?

**Comment by devbazilio** [comment]
It's not ancient browsers, I have logger of all frontend errors and some 
web robots like microsoft Bing and other ones don't have performance 
functions at all, however I muted this error in logger, you can ignore this 
issue, ty for looking.

John Hildenbiddle <notifications@github.com> 6 августа 2019 г. 2:11:46 написал:

**Comment by jhildenbiddle** [comment]
Sounds good. Thanks, @devbazilio.
