### ISSUE TITLE
Documentation: options.silent description incorrect?

### ISSUE THREAD

**Issue by jjz4689** [jhildenbiddle/css-vars-ponyfill#81]
Firstly - thank you for this awesome ponyfill. Very useful for keeping my apps backward-compatible with old browsers (no names... 🤢). Don't know what I'd do without it.

I was reading through the docs and came across the description for the [`options.silent`](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/docs/index.md#silent) property, related to logging out warnings/errors to the console:

>Determines if warning and error messages will be displayed on the console.

>When `true`, messages will be displayed on the console for each warning and error encountered while processing CSS. When `false`, messages will not be displayed on the console but will still be available using the `options.onWarning` and `options.onSuccess` callbacks.

Which suggests setting silent to `true`, _doesn't silence_ the console messages. Inversely, setting it to `false`, _does silence_ console messages.

Am I reading it incorrectly, or is the documentation for silent's `true`|`false` the wrong way round?

I would have thought:
`true` = silence; don't display console messages
`false` = don't silence; display console messages

Thanks.

**Comment by jjz4689** [comment]
### Further suggestion

Might it also be worth adding a second example beneath the description to show what is displayed when `silent` is turned on (`silent: true`), and using the callbacks?

E.g.:
Javascript:
```javascript
cssVars({
  silent: true // don't display any messages
});
```

Console:
```
// nothing
```

---

Javascript:
```javascript
cssVars({
  silent: true, // don't display any messages
  onWarning: console.warn // but still log warnings to the console
  onSuccess: () => console.log('cssVars success!') // and still log success to the console
});
```

Console:

```shell
> cssVars success!
> cssVars(): variable "--fail" is undefined
```

**Comment by jhildenbiddle** [comment]
@jjz4689 --

Apologies for the delayed response. I was focused on other tasks for a few months, but I am now trying to catch up on GitHub issues.

Good catch! I'll update the docs for the next release.
