### ISSUE TITLE
Css Variables undefined if declaring variable with another variable

### ISSUE THREAD

**Issue by LauraZodrow** [jhildenbiddle/css-vars-ponyfill#82]
Just declaring a variable works great in ie11, but when I define another variable with a variable, variable does not work in ie11. 

Variable works:
![Screen Shot 2019-06-24 at 11 24 57 AM](https://user-images.githubusercontent.com/8607970/60038929-c78f3480-9672-11e9-980f-a4ac51e2700d.png)

Declairing variable with variable: 
![Screen Shot 2019-06-24 at 11 22 44 AM](https://user-images.githubusercontent.com/8607970/60038938-ce1dac00-9672-11e9-95a9-1108bc04d0e1.png)

Then the following is not working: 
![Screen Shot 2019-06-24 at 11 27 19 AM](https://user-images.githubusercontent.com/8607970/60039061-150ba180-9673-11e9-8eed-26745af87961.png)

Thanks so much! Awesome ponyfill!

**Comment by tangdaohai** [comment]
@LauraZodrow hi, How to make it work fine in ie11?

**Comment by jhildenbiddle** [comment]
@tangdaohai --

What issue are you having? Feel free to create another issue if you'd like some help troubleshooting.

**Comment by tangdaohai** [comment]
> @tangdaohai --
> 
> What issue are you having? Feel free to create another issue if you'd like some help troubleshooting.

thanks, I know it wont work in ie11.

**Comment by jhildenbiddle** [comment]
@tangdaohai --

To clarify, does the ponyfill not work for your specific scenario (e.g. scoped declarations) or are you just unable to get it to work in IE11? I ask because the ponyfill definitely works in IE11 (it would be pretty pointless if it didn't) with the limitation stated in the README and documentation:

> **Limitations**
> 
> * Custom property declaration support is limited to :root and :host rulesets
> * The use of var() is limited to property values (per W3C specification)

**Comment by tangdaohai** [comment]
@jhildenbiddle 

yes, I violated this rule:

> Custom property declaration support is limited to :root and :host rulesets

I found this problem when I read the documentation again.

thanks.
