### ISSUE TITLE
cssVars(): CSS parse error: missing '}' on minified CSS

### ISSUE THREAD

**Issue by waterplea** [jhildenbiddle/css-vars-ponyfill#84]
Hello. I've ran into this bug, ponyfill gives me an error:
`cssVars(): CSS parse error: missing '}'`
When I have variables inside `@media` queries but the minified CSS removed spaces after `@media` word itself, like this:
`@media{.wrapper::-webkit-scrollbar-thumb{background-color:var(--color-scrollbar)}}`
This is the way Angular 8 minifies CSS files and when I upgraded from 7 — ponyfill started failing :(

**Comment by waterplea** [comment]
Oh, turns out that minifier somehow removed meaningful stuff after that `@media` like `all and ...`, strange I didn't notice that in the first place :) Anyway, might still be useful information that parcing somehow might miss with the curly braces like that.

**Comment by jhildenbiddle** [comment]
Interesting. Thanks, @waterplea.

Even though there's no reason to use a `@media` block without a *media type* (e.g. `all`, `print`, `screen`, etc.) and/or a `media expression` (e.g. `width`, `height`, etc.), doing so is still considered valid CSS. Therefore, the ponyfill should be able to parse both of the following CSS blocks:

```css
/* Works */
@media {}

/* Does not work */
@media{}
```

I'll fix this in the next release.
