### ISSUE TITLE
IE11 CSS XHR error and polyfill file missing

### ISSUE THREAD

**Issue by Gilgaustus** [jhildenbiddle/css-vars-ponyfill#86]
![css ie11 errors](https://user-images.githubusercontent.com/14082571/62572856-b38a4580-b862-11e9-9938-8d794124b851.PNG)

Hello, I am currently attempting to implement the ponyfill but IE11 gives me these errors. It is running in Chrome perfectly but that's not where its needed. Thank you.

**Comment by jhildenbiddle** [comment]
@Gilgaustus --

Those two errors in isolation don't help much. What I can tell you is this:

* The `polyfills.js` error has nothing to do with this ponyfill
* This ponyfill handles CORS requests

If you are using IE within a corporate environment, perhaps your security settings are preventing CORS requests from completing as expected. Other than that, there isn't much help I can offer without more insight into the application.

**Comment by abdul** [comment]
If you add crossorigin="anonymous" as attribute to link tag, you won't hit this issue.

<link crossorigin="anonymous" ....>

**Comment by abrahamhurtado** [comment]
> If you add crossorigin="anonymous" as attribute to link tag, you won't hit this issue.

@abdul Sorry for jumping in so late. How? I tried it your suggestion with no success. But I'm reading from MDN that the `crossorigin` attribute is not supported by IE11.

See [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#browser_compatibility).
