### ISSUE TITLE
css-vars-ponyfill does not work with lit-element

### ISSUE THREAD

**Issue by lamianbu** [jhildenbiddle/css-vars-ponyfill#88]
css-vars-ponyfill work with origin Web Component，but it does not work with lit-element。

I know it is the lit-element‘s issue， but it is more popular than css-vars-ponyfill, so I wish css-vars-ponyfill to support lit-element

**Comment by lamianbu** [comment]
Maybe It is my fault, lit-element has a css var shim.

It is conflict

**Comment by jhildenbiddle** [comment]
@lamianbu --

Correct.

lit-element contains its own method of transforming CSS custom properties to static values. It appears this transformation is handled by [ShadyCSS](https://github.com/webcomponents/polyfills/tree/master/packages/shadycss), specifically by the [ScopingShim](https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#about-scopingshim) it includes:

> ScopingShim works by rewriting style contents and transforming selectors to enforce scoping. Additionally, if CSS Custom Properties is not detected, ScopingShim will replace CSS Custom Property usage with realized values.

lit-element transforms CSS custom properties to static values *before* appending styles to the DOM. This means that the CSS custom properties you've defined in your lit-element's JavaScript source are never added to the DOM, so there is nothing for css-vars-ponyfill to transform.

The standard [web component polyfill](https://www.webcomponents.org/polyfills/) also includes ShadyCSS, but it does not share the same ScopingShim behavior of transforming custom properties to static values. This allows css-vars-ponyfill to work as expected.

Hope this helps. At this point, I think they best option to is to ask the lit-element team if it is possible to disable the ScopingShim's CSS custom property transformations.

**Comment by jhildenbiddle** [comment]
I've created an issue within the ShadyCSS repo: https://github.com/webcomponents/polyfills/issues/197
