### ISSUE TITLE
When document contains <header> css-var-ponyfill is wrongly inserted

### ISSUE THREAD

**Issue by helabenkhalfallah** [jhildenbiddle/css-vars-ponyfill#89]
Hello,

When my page had this structure :
```
<head >
      <style>som style </style>
      <style id="css-vars-ponyfill" >
</head>
<body>
     <div>
     </div>
</body>
```

I get css-vars-ponyfill inserted correctly at `<head>`.

But when it has this structure :
```
<head >
     <style>som style </style>
</head>
<body>
  <div>
     <header>
     </header>
     <style>som style </style>
      <style id="css-vars-ponyfill" >
   </div>
</body>
```

I get css-vars-ponyfill inserted after **header** and not inside head (wrong).
This wrong insert override all my css variables and I got a bad display.
Have you an idea ?

Also I use css-vars-ponyfill only for colors but I get inside css-vars-ponyfill tag all my css style.

Browser: IE 11.

Thanks :)

**Comment by ameem91** [comment]
@helabenkhalfallah which version are you using? I had a similar issue with style tags being incorrectly inserted when using version 1.17.2. But when I upgraded to the latest version (2.1.1), it was fixed.

**Comment by helabenkhalfallah** [comment]
Hello @ameem91 thank you so much, everything is OK after upgrade. :) :)

**Comment by varxnnn** [comment]
@ameem91 are you talking about css-vars-ponyfill's version?
