### ISSUE TITLE
Not updating legacy values

### ISSUE THREAD

**Issue by linearza** [jhildenbiddle/css-vars-ponyfill#90]
Hi, so were implementing your lib, which is great thank you!

Everything works as expected, however for some reason legacy values dont get updated, am I missing something?
For example if I start with the following where `--theme` is `green`, and have `preserveVars` as `true`:
```
background: var(---theme);
```
Then it generates the following:
```
background: green;
background: var(---theme);
```
But then on updating `--theme` it successfully updates the modern var syntax, but the legacy property stays the same:
```
background: green;
background: var(---theme); // this gets updated
```

It seems like Im missing something very basic!

Thanks!

**Comment by linearza** [comment]
Btw, Ive browsed all the closed issues and am using a standard approach where i just call `cssVars();` and then update the variables via `options.variables` as you suggest in other issues. I also added a `MutationObserver` polyfill for IE, but I would expect on chrome that it updates both the modern syntax and older syntax at the same time when `onlyLegacy` is `true`, right?

**Comment by linearza** [comment]
For some reason its working now... Phew! Closing, and thanks again!

**Comment by jhildenbiddle** [comment]
My fastest fix ever. 😉 

Glad it's working. Happy to help if you run into any issues moving forward.
