### ISSUE TITLE
Framework7 cannot be used

### ISSUE THREAD

**Issue by cn-yezi** [jhildenbiddle/css-vars-ponyfill#91]
@jhildenbiddle 
Thank you very much for writing such a script, looking for the entire Internet, only you have done this.

When I want to use css-vars-ponyfill to let Framework7 support IE, I found that it can't meet expectations. The code is as follows, I hope you can give a solution.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.bootcss.com/framework7/5.0.0-beta.14/css/framework7.bundle.css" rel="stylesheet">
    <style>
        html{
            color: var(--f7-theme-color);
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"></script>
    <script>   
    cssVars({
        // Options...
        onlyLegacy: false,
        onComplete(cssText, styleElms, cssVariables, benchmark) {
            console.log(`cssVars()): ${cssText}`);
        }
    });
    </script>
</head>
<body>
    
</body>
</html>
```

**Comment by jhildenbiddle** [comment]
Hi @cn-yezi --

Per the docs, css-vars-ponyfill only supports `:root` and `:host`-level custom property declarations:

> Custom property declaration support is limited to :root and :host rulesets

Looking at the Framework7 CSS, I can see custom properties declarations scoped within `@media` rules and classes which the ponyfill does not support. The end result is that the ponyfill only be able to process some but not all of the Framework7 CSS.

For example, the following declarations will be processed from the Framework7 CSS:

```css
:root {
  --f7-theme-color: #007aff;
  --f7-theme-color-rgb: 0, 122, 255;
  --f7-theme-color-shade: #0066d6;
  --f7-theme-color-tint: #298fff;
  --f7-safe-area-left: 0px;
  --f7-safe-area-right: 0px;
  --f7-safe-area-top: 0px;
  --f7-safe-area-bottom: 0px;
  --f7-safe-area-outer-left: 0px;
  --f7-safe-area-outer-right: 0px;
  --f7-device-pixel-ratio: 1;
}
```

But the following declarations will not:

```css
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx) {
  :root {
    --f7-device-pixel-ratio: 2;
  }
}
```
```css
.ios {
  --f7-font-family: -apple-system, SF Pro Text, SF UI Text, system-ui, Helvetica Neue, Helvetica, Arial, sans-serif;
  --f7-text-color: #000;
  --f7-line-height: 1.4;
}
```

A detailed explanation of why this limitation exists is available here: https://github.com/jhildenbiddle/css-vars-ponyfill/issues/26

Hope this clarifies the issue and the ponyfill's limitations.
