### ISSUE TITLE
Remove calc keywords from HSL colors for legacy browser compatibility

### ISSUE THREAD

**Issue by fynnfeldpausch** [jhildenbiddle/css-vars-ponyfill#94]
We are using `calc()` keywords in HSL colors. However, this is not supported by IE11 and we would love to see this feature in your lib. Here is an example (https://codepen.io/fynnfeldpausch/pen/NWKorJM). This should work for both integer and floating point numbers:

**Given Input:**
```
:root {
  --h: 120;
  --s: 50%;
  --l: 50.123456%
}

.test {
  color: hsl(var(--h), var(--s), calc(var(--l) - 12%));
}
```

**Actual Output:**
```
.test {
    color: hsl(120, 50%, calc(50.123456% - 12%));
}
```

**Expected Output:**
```
.test {
    color: hsl(120, 50%, 38.123456%);
}
```

**Comment by fynnfeldpausch** [comment]
We inserted the following code as a fix. Did not provide a PR as this is not fully tested (yet) but maybe it is a good starting point:

```
/**
 * Removes calc keywords from HSL colors for legacy browser compatibility.
 * Example: hsl(240, 45%, calc(30% + 20%)) => hsl(240, 45%, 50%)
 *
 * @param {array} rules
 */
function fixHslCalc(rules) {
    const reHslExp = /hsla?\(/;
    const reCalcExp = /(-[a-z]+-)?calc\(/;

    rules.forEach(function(rule) {
        if (rule.declarations) {
            rule.declarations.forEach(function(decl) {
                let oldValue = decl.value;
                let newValue = "";
                while (reHslExp.test(oldValue)) {
                    const rootCalc = balancedMatch("(", ")", oldValue || "");
                    oldValue = oldValue.slice(rootCalc.end);
                    while (reCalcExp.test(rootCalc.body)) {
                        const nestedCalc = balancedMatch(reCalcExp, ")", rootCalc.body);
                        rootCalc.body = nestedCalc.pre + resolveExpression(nestedCalc.body) + nestedCalc.post;
                    }
                    newValue += rootCalc.pre + "(" + rootCalc.body;
                    newValue += !reHslExp.test(oldValue) ? ")" + rootCalc.post : "";
                }
                decl.value = newValue || decl.value;
            });
        }
    });
}

/**
* Evaluates the given string expression.
* Example: 30% + 20% => 50%
*
* @param {string} expr
*/
function resolveExpression(expr) {
    const parts = expr.split(/(\+|\-)/);
    let sum = (parts[0] || "").match(/^\s*(\d+)%\s*$/);
    if (!sum) {
        return expr;
    }

    sum = parseInt(sum[1]);
    for (let i = 1; i < parts.length - 1; i+=2) {
        const num = parts[i + 1].match(/^\s*(\d+)%\s*$/);
        if (num && parts[i] === "+") {
            sum += parseInt(num[1]);
        } else if (num && parts[i] === "-") {
            sum -= parseInt(num[1]);
        } else {
            return expr;
        }
    }
    return sum + "%";
}
```

**Comment by jhildenbiddle** [comment]
Hi @fynnfeldpausch,

Thank you for creating the PR. Please see the comments associated with the PR.

The use of `calc()` in color functions is a known issue in legacy browsers. Unfortunately, as mentioned in the comments left for the PR, the fixes provided above and in the PR are only able to reduce matched-unit (e.g. `calc(1px + 1px)`) or unit+unitless (e.g. `calc(1px * 5)`) calculations. Mixed-unit calculations (e.g. `calc(1em + 1px)`) will not be reduced and will therefore continue to fail. It is for this reason that neither fix is a good candidate for adding to the ponyfill.

The good news is that you can accomplish the same thing without modifying the source by using the `onComplete` callback. See the following demo for details:

* https://stackblitz.com/edit/css-vars-ponyfill-94?file=index.js

Hope this helps.
